Traceback (most recent call last):
  File "/scratch/f/F.Conoscenti/netket_venv1/lib/python3.11/site-packages/einops/einops.py", line 532, in reduce
    return _apply_recipe(
           ^^^^^^^^^^^^^^
  File "/scratch/f/F.Conoscenti/netket_venv1/lib/python3.11/site-packages/einops/einops.py", line 235, in _apply_recipe
    init_shapes, axes_reordering, reduced_axes, added_axes, final_shapes, n_axes_w_added = _reconstruct_from_shape(
                                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/f/F.Conoscenti/netket_venv1/lib/python3.11/site-packages/einops/einops.py", line 188, in _reconstruct_from_shape_uncached
    raise EinopsError(f"Shape mismatch, can't divide axis of length {length} in chunks of {known_product}")
einops.EinopsError: Shape mismatch, can't divide axis of length 16 in chunks of 6

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/scratch/f/F.Conoscenti/Thesis_QSL/ViT_Heisenberg/run_ViT.py", line 95, in <module>
    params = vit_module.init(subkey, spin_configs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/f/F.Conoscenti/Thesis_QSL/ViT_Heisenberg/ViT_model.py", line 309, in __call__
    z_plus = vit(spins)
             ^^^^^^^^^^
  File "/scratch/f/F.Conoscenti/Thesis_QSL/ViT_Heisenberg/ViT_model.py", line 274, in __call__
    y = Encoder(
        ^^^^^^^^
  File "/scratch/f/F.Conoscenti/Thesis_QSL/ViT_Heisenberg/ViT_model.py", line 208, in __call__
    x = l(x)
        ^^^^
  File "/scratch/f/F.Conoscenti/Thesis_QSL/ViT_Heisenberg/ViT_model.py", line 180, in __call__
    x = x + self.attn(self.layer_norm_1(x))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/f/F.Conoscenti/Thesis_QSL/ViT_Heisenberg/ViT_model.py", line 118, in __call__
    v = rearrange(
        ^^^^^^^^^^
  File "/scratch/f/F.Conoscenti/netket_venv1/lib/python3.11/site-packages/einops/einops.py", line 600, in rearrange
    return reduce(tensor, pattern, reduction="rearrange", **axes_lengths)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/f/F.Conoscenti/netket_venv1/lib/python3.11/site-packages/einops/einops.py", line 542, in reduce
    raise EinopsError(message + "\n {}".format(e))
einops.EinopsError:  Error while processing rearrange-reduction pattern "batch n_patches (n_heads d_eff) -> batch n_patches n_heads d_eff".
 Input tensor shape: (10, 4, 16). Additional info: {'n_heads': 6}.
 Shape mismatch, can't divide axis of length 16 in chunks of 6
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
[CpuDevice(id=0)]
[CpuDevice(id=0)]
srun: error: th-cl-hua06: task 0: Exited with exit code 1
srun: Terminating StepId=9912860.0
